"""empty message

Revision ID: 784ae03bb502
Revises: 0ef1a742d6d1
Create Date: 2024-12-16 00:36:15.148303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784ae03bb502'
down_revision = '0ef1a742d6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usdt_wallet', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('usdt_wallet')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
